# Site Settings
title: Simulated Biology
tagline: You think Kunkka knew I stole his rum?
author:
  name: "Matthew Ralston"
  email: mralston.development@gmail.com
  url: "http://matthewralston.us"
  twitter: "TheWaterAndWind"


description: >
  Periodic Letters, Blog Content, Contract Research
baseurl: "/"
markdown: kramdown
url: "http://localhost:4000"
permalink: pretty
#favicon: favicon.ico

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: csrhymes


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-toc
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-158080285-1

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Matt Ralston"
      layout: post
      image: /assets/img/dna-3888228__480.jpg
      show_sidebar: true



kramdown:
  input: GFM
  syntax_highlighter: rouge
#highlighter: rouge

footer_menu: example_footer_menu

version: "0.0.1"
# toc:
#   min_level: 2 # Default 1
#   max_level: 4 # Default 6


collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
    